services:

  api:
    build: ./back-end
    ports:
      - "4000:4000"
    env_file:
      - ./back-end/.env
  frontend:
    build: ./front-end
    ports:
      - "5173:5173"
    depends_on:
      - api